:PROPERTIES:
:header-args:emacs-lisp: :lexical t
:END:
* My Doom Emacs Configuration

Enable lexical binding by default for tangle output.

#+begin_src emacs-lisp
;;;; -*- lexical-binding: t; -*-
#+end_src

Set user information.

#+begin_src emacs-lisp
(setq user-full-name "Russell Smith"
      user-mail-address "russell.smith7502@gmail.com")
#+end_src

** User Interface

Easy on the eyes font and theme.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font Mono"
                           :size 13
                           :weight 'normal))

(setq doom-theme 'zenburn)
#+end_src

Enable lines numbers globaly.

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

 When wrapping is enabled, [[help:hl-line-mode][hl-line-mode]] highlights the logical line (the block of text) by default. That defeats the purpose of wrapping, so change it to only highlight visual lines.

#+begin_src emacs-lisp
(defun visual-line-range ()
  (save-excursion
    (cons (progn (vertical-motion 0) (point))
          (progn (vertical-motion 1) (point)))))

(setq hl-line-range-function #'visual-line-range)
#+end_src

** General Editing

Bind some useful commands, I use everywhere.

#+begin_src emacs-lisp
(map! "C-s" 'consult-line)
#+end_src

Avy is the best way to jump around in Emacs. Enable all windows as potential targets. To make returning after jumping with Avy easier, also configure [[fn:pop-global-mark][pop-global-mark]] to switch windows if possible.

#+begin_src emacs-lisp
(setq avy-all-windows t)

(map! "C-." 'avy-goto-char-timer)

(define-advice pop-global-mark (:around (pgm) use-display-buffer)
  "Make `pop-to-buffer' jump buffers via `display-buffer'."
  (cl-letf (((symbol-function 'switch-to-buffer) #'pop-to-buffer))
    (funcall pgm)))
#+end_src

Automatically inserting newlines when moving to the next line is useful when auto-complete is active.

#+begin_src emacs-lisp
(setq next-line-add-newlines t)
#+end_src

*** Word Wrapping

Doom by default do not provide a way to toggle word wrapping, so I created a module, ++word-wrap, that provides a mode to implement it. ++word wrap also toggles the word-wrap module, which enhances the default behavior of visual lines, if it's enabled. I use [[fn:++word-wrap-mode][++word-wrap-mode]] in my config whenever I want to enable wrapping.

Wrap lines at the [[help:fill-column][fill-column]] and disable [[help:auto-fill-mode][auto-fill-mode]] when wrapping.

#+begin_src emacs-lisp
(setq +word-wrap-fill-style 'soft)
#+end_src

*** Paragraph Filling

When I decided to switch to wrapping for Org mode, I tried to unfill all my paragraphs but realized this feature is not provided natively. Here is an implementation based on one from the [[https:www.emacswiki.org/emacs/UnfillParagraph][Emacs Wiki]]: mine includes a wrapper function which allows for deciding on filling or unfilling via the prefix argument.

#+begin_src emacs-lisp
(defun unfill-paragraph (&optional region)
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive (progn (barf-if-buffer-read-only) '(t)))
  (let ((fill-column (point-max))
        ;; This would override `fill-column' if it's an integer.
        (emacs-lisp-docstring-fill-column t))
    (fill-paragraph nil region)))

(defun my-fill-paragraph (&optional region unfill)
  (interactive (progn (barf-if-buffer-read-only)
                      (list t current-prefix-arg)))
  (let ((unfill (or unfill 1)))
    (if (or (eq unfill '-)
            (cl-minusp unfill))
        (unfill-paragraph region)
      (fill-paragraph t region))))

(map! "M-q" 'my-fill-paragraph)
#+end_src

** Completion

I had trouble disabling certain Corfu bindings. Company works fine, so use it for now.

#+begin_src emacs-lisp
(after! company
  (setq company-idle-delay 0.21
        company-show-quick-access t
        company-tooltip-limit 20
        company-tooltip-align-annotations t)
  (map! :map company-active-map
        "C-n" nil
        "C-p" nil))
#+end_src

** Org Mode

Set org mode directory.

#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src

Extend fill column.

#+begin_src emacs-lisp
(setq-hook! org-mode
  fill-column 120)
#+end_src

Enable word wrapping.

#+begin_src emacs-lisp
;;(add-hook! org-mode #'++word-wrap-mode)
#+end_src

** Programming

I use these modes in every programming language.

#+begin_src emacs-lisp
(add-hook! prog-mode '(rainbow-delimiters-mode-enable display-fill-column-indicator-mode))
#+end_src

Configure the tab key to always indent line to the correct indention.

#+begin_src emacs-lisp
(setq-hook! prog-mode
  tab-always-indent t)
#+end_src

*** C/C++

Set the default style to the Linux kernel's style, but use a 4 space indent.

#+begin_src emacs-lisp
(setq-hook! '(c-ts-mode-hook c++-ts-mode-hook)
  c-ts-mode-indent-style 'linux
  c-ts-mode-indent-offset 4)
#+end_src

Disable auto-formating by default. If I want to use clang-format, I configure that per project.

#+begin_src emacs-lisp
(add-to-list '+format-on-save-disabled-modes 'c++-ts-mode)
(add-to-list '+format-on-save-disabled-modes 'c-ts-mode)
#+end_src

I prefer the new treesitter based mode, but the old cc-mode has some useful commands. I use the hungry deletion commands globally.

#+begin_src emacs-lisp
(use-package! cc-mode
  :bind (("C-x DEL" . c-hungry-delete-backwards)
         ("C-x C-d" . c-hungry-delete-forward)))
#+end_src

*** Common Lisp

Sly can become slow for some reason during completion, so disable idle completion.

#+begin_src emacs-lisp
(setq-hook! lisp-mode
  company-idle-delay nil)
#+end_src

Bind some useful smartparen commands not bound by default.

#+begin_src emacs-lisp
(map! :after smartparens
      :map smartparens-mode-map
      "C-<right>" 'sp-forward-slurp-sexp
      "M-<right>" 'sp-forward-barf-sexp
      "C-<left>" 'sp-backward-slurp-sexp
      "M-<left>" 'sp-backward-barf-sexp)
#+end_src
