#+STARTUP: content
:PROPERTIES:
:header-args:emacs-lisp: :lexical t
:END:
* My Doom Emacs Configuration
Enable lexical binding by default for tangle output.

#+begin_src emacs-lisp
;;;; -*- lexical-binding: t; -*-
#+end_src

Set my personal information.

#+begin_src emacs-lisp
(setq user-full-name "Russell Smith"
      user-mail-address "russell.smith7502@gmail.com")
#+end_src

** User Interface
*** Theme and Fonts
Zenburn in comparison to modern high contrast themes might appear ugly but is much easier on the eyes late at night. The doom-themes version is configured to look great with Doom's extensions.

#+begin_src emacs-lisp
(setq doom-theme 'doom-zenburn)
#+end_src

JetBrainsMono is also great for preventing eye strain. The Nerd Font version supports icons, which are used extensively by Doom.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font Mono"
                           :size 13
                           :weight 'normal))
#+end_src

*** Line Numbers
Enable lines numbers globally.

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

*** Line Wrapping
Wrap lines at the [[help:fill-column][fill-column]] and disable [[help:auto-fill-mode][auto-fill-mode]] when wrapping.

#+begin_src emacs-lisp
(setq +word-wrap-fill-style 'soft)
#+end_src

When wrapping is enabled, [[help:hl-line-mode][hl-line-mode]] highlights the logical line by default. This defeats the purpose of wrapping, so change it to only highlight visual lines. This is not perfect because the end of the previous line is highlighted if it contains whitespace. Hopefully, I'll find a fix for this one day.

#+begin_src emacs-lisp
(defun visual-line-range ()
  (save-excursion
    (cons (progn (vertical-motion 0) (point))
          (progn (vertical-motion 1) (point)))))

(setq hl-line-range-function #'visual-line-range)
#+end_src

*** Whitespace

Doom hijacks [[fn:whitespace-mode][whitespace-mode]] by default to highlight possible incorrect indentation. I like this behavior, but it is not configurable by default. I forked the whitespace module and refactored it to allow for toggling the behavior.

#+begin_src emacs-lisp
(when (modulep! :personal whitespace)
  (map! :map doom-leader-toggle-map
        :desc "Whitespace Style" "W" #'+whitespace/toggle-style))
#+end_src

** Editing
Rebind the default isearch keybinding to consult.

#+begin_src emacs-lisp
(map! "C-s" 'consult-line)
#+end_src

Automatically inserting newlines when moving to the next line is useful when auto-complete is active.

#+begin_src emacs-lisp
(setq next-line-add-newlines t)
#+end_src

*** Avy

Avy is the best way to jump to any text on screen.

#+begin_src emacs-lisp
(map! "C-." 'avy-goto-char-timer)

(setq avy-all-windows t)
#+end_src

To make returning after jumping with Avy easier, configure [[fn:pop-global-mark][pop-global-mark]] to switch windows if possible.

#+begin_src emacs-lisp
(define-advice pop-global-mark (:around (pgm) use-display-buffer)
  "Make `pop-to-buffer' jump buffers via `display-buffer'."
  (cl-letf (((symbol-function 'switch-to-buffer) #'pop-to-buffer))
    (funcall pgm)))
#+end_src

Avy can also be combined with Embark. This allows for selecting and acting on any text on screen without ever moving the cursor.

#+begin_src emacs-lisp
(defun avy-action-embark (pt)
  (unwind-protect
      (save-excursion
        (goto-char pt)
        (embark-act))
    (select-window
     (cdr (ring-ref avy-ring 0))))
  t)

(after! avy
 (setf (alist-get ?o avy-dispatch-alist) 'avy-action-embark))
#+end_src

*** S-Expressions

Bind some useful smartparens commands not bound by default.

#+begin_src emacs-lisp
(map! :after smartparens
      :map smartparens-mode-map
      "C-<right>" 'sp-forward-slurp-sexp
      "M-<right>" 'sp-forward-barf-sexp
      "C-<left>" 'sp-backward-slurp-sexp
      "M-<left>" 'sp-backward-barf-sexp)
#+end_src

*** Paragraph Filling

When I decided to switch to wrapping for Org mode, I tried to unfill all my paragraphs but realized this feature is not provided natively. Here is an implementation based on one from the [[https:www.emacswiki.org/emacs/UnfillParagraph][Emacs Wiki]]: mine includes a wrapper function which allows for deciding on filling or unfilling via the prefix argument.

#+begin_src emacs-lisp
(defun unfill-paragraph (&optional region)
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive (progn (barf-if-buffer-read-only) '(t)))
  (let ((fill-column (point-max))
        ;; This would override `fill-column' if it's an integer.
        (emacs-lisp-docstring-fill-column t))
    (fill-paragraph nil region)))

(defun my-fill-paragraph (&optional region unfill)
  (interactive (progn (barf-if-buffer-read-only)
                      (list t current-prefix-arg)))
  (let ((unfill (or unfill 1)))
    (if (or (eq unfill '-)
            (cl-minusp unfill))
        (unfill-paragraph region)
      (fill-paragraph t region))))

(map! "M-q" 'my-fill-paragraph)
#+end_src

** Workspaces
By default doom loads a project into the main workspace if it’s empty. I prefer to reserve the main workspace for ad hoc editing of files. So always open up a new workspace when opening up a project.

#+begin_src emacs-lisp
(setq +workspaces-on-switch-project-behavior t)
#+end_src

** Completion
*** Corfu
Company mode used to be the hip auto-complete framework. However, Corfu provides the same features while also integrating better with the native Emacs completion ecosystem.

#+begin_src emacs-lisp
(after! corfu
  (setq corfu-auto t
        corfu-cycle t
        corfu-on-exact-match 'insert))
#+end_src

I used to really like constantly having completion options available, but completion backend speeds and results are not always reliable enough to enable this by default. Now, I use tab completion by default, which stays out of my way unless I need it.

#+begin_src emacs-lisp
(setq tab-always-indent 'complete) ; indent or complete line
#+end_src

*** Company
At the moment, I am testing out Corfu. These are my old Company settings.

#+begin_src emacs-lisp
(after! company
  (setq company-idle-delay 0.21
        company-show-quick-access t
        company-tooltip-limit 20
        company-tooltip-align-annotations t)
  (map! :map company-active-map
        "C-n" nil
        "C-p" nil))
#+end_src

** Spell Checking
This is a temporary fix for the way the spell module handles the personal dictionary. See [[https:github.com/doomemacs/doomemacs/issues/6246][this issue]] for details.

#+begin_src emacs-lisp
(after! spell-fu
  (unless (file-exists-p ispell-personal-dictionary)
    (make-directory (file-name-directory ispell-personal-dictionary) t)
    (with-temp-file ispell-personal-dictionary
      (insert (format "personal_ws-1.1 %s 0\n" ispell-dictionary)))))
#+end_src

** Org Mode
#+begin_src emacs-lisp
(setq org-directory "~/Documents/Org/"
      org-startup-indented t
      org-auto-align-tags nil
      org-tags-column 0
      org-catch-invisible-edits 'show-and-error
      org-special-ctrl-a/e t
      org-insert-heading-respect-content t
      org-hide-emphasis-markers t
      org-pretty-entities t
      org-agenda-tags-column 0
      org-ellipsis "…")
#+end_src

Modern monitors are wide enough that longer lines are acceptable. I also rarely have more than two horizontal windows open at a time.

#+begin_src emacs-lisp
(setq-hook! org-mode fill-column 120)
#+end_src

I prefer the headings to appear larger than the rest of the text on screen to make them more readable. I wrote [[fn:my-set-org-header-style][my-set-org-header-style]] to make changing the styles of all the header faces quicker and less error prone. Currently, this source block is disabled since I'm using Org Modern.

#+begin_src emacs-lisp :tangle no
(cl-defmacro my-set-org-header-style ((top-level-height height-diff) &rest args)
  "Set the height of Org head lines with evenly spaced height differences."
  (declare (indent defun))
  `(progn
     ,@(cl-loop for height = top-level-height then (- height height-diff)
                for level from 1
                while (>= height 1)
                collect (let ((level-name (intern (format "org-level-%d" level))))
                          `(set-face-attribute ',level-name nil
                            ,@args)))))

(after! org
  (my-set-org-header-style (1.6 0.2)
    :weight 'bold))
#+end_src

I use the Org Modern package to beautify the Org syntax.

#+begin_src emacs-lisp
(use-package! org-modern
  :hook ((org-mode . org-modern-mode)))

(use-package! org-modern-indent
  :hook ((org-mode . org-modern-indent-mode)))
#+end_src

** Programming
I use these modes in every programming language.

#+begin_src emacs-lisp
(add-hook! prog-mode '(rainbow-delimiters-mode display-fill-column-indicator-mode))
#+end_src

Configure the tab key to always indent line to the correct indention.

#+begin_src emacs-lisp
(setq-hook! prog-mode tab-always-indent t)
#+end_src

*** Language Servers

Enables some useful UI features that are Doom disables by default.

#+begin_src emacs-lisp
(setq lsp-headerline-breadcrumb-enable t)
#+end_src

*** C/C++

Set the default style to the Linux kernel's style, but use a 4 space indent.

#+begin_src emacs-lisp
(setq-hook! '(c-ts-mode-hook c++-ts-mode-hook)
  c-ts-mode-indent-style 'linux
  c-ts-mode-indent-offset 4)
#+end_src

Disable auto-formating by default. If I want to use clang-format, I configure that per project.

#+begin_src emacs-lisp
(add-to-list '+format-on-save-disabled-modes 'c++-ts-mode)
(add-to-list '+format-on-save-disabled-modes 'c-ts-mode)
#+end_src

I prefer the new treesitter based mode, but the old cc-mode has some useful commands. I use the hungry deletion commands globally.

#+begin_src emacs-lisp
(use-package! cc-mode
  :bind (("C-x DEL" . c-hungry-delete-backwards)
         ("C-x C-d" . c-hungry-delete-forward)))
#+end_src

*** Common Lisp

Sly can become slow for some reason during completion, so disable idle completion.

#+begin_src emacs-lisp
(setq-hook! lisp-mode
  company-idle-delay nil)
#+end_src

Often in projects using the iter macro from the Iterate package, Sly runs into indention collisions, so override it here.

#+begin_src emacs-lisp
(after! sly
  (put 'iter 'common-lisp-indent-function 0))
#+end_src
